if status is-interactive
  abbr -a gaa 'git add .'
  abbr -a gst 'git status'
  abbr -a gsm 'git switch main'
  abbr -a gpu 'git push'
  abbr -a gpuo 'git push -u origin (git branch --show-current)'
  abbr -a gpuf 'git push -f'
  abbr -a gcm --set-cursor 'git commit -m "%"'
  abbr -a gcam 'git commit --amend'
  abbr -a gcan 'git commit --amend --no-edit'
  abbr -a gcmn --set-cursor 'git commit --no-verify -m "%"'
  abbr -a gsmp 'git switch main && git fetch --all && git pull'
  abbr -a gpl 'git pull'
  abbr -a gsn 'git switch -c'
  abbr -a gsw 'git switch'
  abbr -a gpr 'gh pr view --web || gh pr create --web'
  abbr -a gr 'gh repo view --web'
  abbr -a gl 'git l'
  abbr -a gla 'git la'
end
