[[file]]
source = ".zshrc"
target = "~/.zshrc"

[[file]]
source = ".zimrc"
target = "~/.zimrc"

[[file]]
source = "config/cache.zsh"
target = "~/.zsh/cache.zsh"

[[file]]
source = "config/shared.zsh"
target = "~/.zsh/shared.zsh"

# Platform-specific config, selected at deploy time
[[file]]
source = "config/macos.zsh"
target = "~/.zsh/os.zsh"
when = "patina.os == 'macos'"

[[file]]
source = "config/linux.zsh"
target = "~/.zsh/os.zsh"
when = "patina.os == 'linux'"

[[file]]
source = "config/windows.zsh"
target = "~/.zsh/os.zsh"
when = "patina.os == 'windows'"

[[file]]
source = "config/user-abbreviations.zsh"
target = "~/.config/zsh-abbr/user-abbreviations"
