#!/usr/bin/env fish
# Generates ~/.config/fish/conf.d/_local-env.fish with HOSTNAME, LANG, TZ, SHELL.
# Fish has no .zshenv equivalent; this writes a per-machine conf.d snippet that
# fish auto-loads on every shell start.
#
# Unlike setup-msys2-zsh.zsh, this is NOT a perf optimization — fish doesn't source
# /etc/profile, so it never had subprocess startup spawns. This exists for parity
# so tools reading $LANG/$TZ/$HOSTNAME behave the same regardless of how fish
# was launched (Windows Terminal vs MSYS2 vs PowerShell).
#
# Run once on each machine (or after changing timezone/locale):
#   just setup-msys2-fish

if not string match -q -- '*_NT-*' (uname -s)
    echo "setup-msys2-fish: MSYS2 only, nothing to do on "(uname -s) >&2
    exit 1
end

set -l env_file "$HOME/.config/fish/conf.d/_local-env.fish"

set -l _hostname $hostname
set -l _lang (/usr/bin/locale -uU)
set -l _tz (/usr/bin/tzset)
set -l _shell (status fish-path)

echo "Detected values:"
echo "  HOSTNAME=$_hostname"
echo "  LANG=$_lang"
echo "  TZ=$_tz"
echo "  SHELL=$_shell"

mkdir -p (dirname $env_file)

printf '%s\n' \
    "# Generated by setup-msys2-fish.fish; do not edit by hand." \
    "# Regenerate with: just setup-msys2-fish" \
    "set -gx HOSTNAME $_hostname" \
    "set -gx LANG $_lang" \
    "set -gx TZ $_tz" \
    "set -gx SHELL $_shell" \
    >$env_file

echo ""
echo "Wrote $env_file. Restart fish for changes to take effect."
