## Shared config is loaded after platform specific configs

# pnpm
export PNPM_HOME="~/.pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

# Flutter version management
export FVM_CACHE_PATH="$HOME/.fvm"
export PATH="$PATH:$HOME/.fvm/default/bin"

# Aliases
alias ls="lsd -a"
alias vi="nvim"
alias vim="nvim"
alias vcpkg="$HOME/github/vcpkg/vcpkg"
alias cd="z"

# Abbreviations
abbr --quiet -S gaa="git add ."
abbr --quiet -S gst="git status"
abbr --quiet -S gsm="git switch main"
abbr --quiet -S gpu="git push"
abbr --quiet -S gpuo="git push -u origin \"\$(git branch --show-current)\""
abbr --quiet -S gpuf="git push -f"
abbr --quiet -S gcm="git commit -m"
abbr --quiet -S gcam="git commit --amend --no-edit"
abbr --quiet -S gcmnf="git commit --no-verify -m"
abbr --quiet -S gsmp="git switch main && git pull"
abbr --quiet -S gpl="git pull"
abbr --quiet -S gsn="git switch -c"
abbr --quiet -S gsw="git switch"
abbr --quiet -S gop="gh browse --branch \"\$(git branch --show-current)\""
abbr --quiet -S gopm="gh browse"
abbr --quiet -S gl="git l"
abbr --quiet -S gla="git la"

export FZF_DEFAULT_OPTS=" \
--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"

# This script was automatically generated by the broot program
# More information can be found in https://github.com/Canop/broot
# This function starts broot and executes the command
# it produces, if any.
# It's needed because some shell commands, like `cd`,
# have no useful effect if executed in a subshell.
function br {
    local cmd cmd_file code
    cmd_file=$(mktemp)
    if broot --outcmd "$cmd_file" "$@"; then
        cmd=$(<"$cmd_file")
        command rm -f "$cmd_file"
        eval "$cmd"
    else
        code=$?
        command rm -f "$cmd_file"
        return "$code"
    fi
}

eval "$(zoxide init zsh)"
eval "$(fnm env --use-on-cd)"
eval "$(starship init zsh)"
